project:
  type: website
  output-dir: docs

website:
  title: "portafolio docente"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: teaching.qmd
        text: Docencia
      - href: evaluation.qmd
        text: Evaluación
      - href: innovation.qmd
        text: Innovación

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script src="https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js"></script>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap" rel="stylesheet">

