project:
  type: website
  output-dir: docs

website:
  title: "Ana Moreno Núñez"
  navbar:
    logo: images/logo.svg
    right:
      - href: index.qmd
        text: Inicio
      - href: teaching.qmd
        text: Docencia
      - href: evaluation.qmd
        text: Evaluación
      - href: innovation.qmd
        text: Innovación

format:
  html:
    theme: default
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">
include-in-header:
  - text: |
      <link rel="stylesheet" href="assets/academicons/academicons.min.css">

