project:
  type: website
  output-dir: docs

website:
  title: "TEMU-UAM"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: part0.qmd
        text: comenzar
      - href: part1.qmd
        text: comprender
      - href: part2.qmd
        text: afinar
      - href: part3.qmd
        text: acompa√±ar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script src="https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js"></script>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Lora:wght@400;500;600&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
