project:
  type: website
  output-dir: docs

website:
  title: "Ana Moreno Núñez"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: teaching.qmd
        text: Docencia
      - href: evaluation.qmd
        text: Evaluación
      - href: innovation.qmd
        text: Innovación

format:
  html:
    theme: default
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script src="https://code.iconify.design/iconify-icon/2.1.0/iconify-icon.min.js"></script>

