project:
  type: website
  output-dir: docs

website:
  title: "Ana Moreno Núñez"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: teaching.qmd
        text: Docencia
      - href: evaluation.qmd
        text: Evaluación
      - href: innovation.qmd
        text: Innovación

format:
  html:
    css: styles.css
